### ISSUE TITLE
@next/font -> next/font migration Issue

### ISSUE THREAD

**Issue by AndrewDongminYoo** [AndrewDongminYoo/AndrewDongminYoo.vercel#8]
```shell
yarn dev # npx next dev
```

Error code below...

```log
AbortError: The user aborted a request.
    at abort (./node_modules/next/dist/compiled/node-fetch/index.js:1:65190)
    at EventTarget.abortAndFinalize (./node_modules/next/dist/compiled/node-fetch/index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at EventTarget.dispatchEvent (node:internal/event_target:677:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at Timeout.<anonymous> (./node_modules/next/dist/compiled/@next/font/dist/google/fetch-font-file.js:24:51)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  type: 'aborted'
}
```

**Comment by AndrewDongminYoo** [comment]
I think it was because I had @next/font installed and using it. Migrating to next/font as recommended by next seems to have fixed it. At least for now.

```log
error - Failed to download `Noto Sans KR` from Google Fonts. Using fallback font instead.
event - compiled client and server successfully in 5.1s (194 modules)
warn  - Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14. You can migrate by running `npx @next/codemod@latest built-in-next-font .`. Read more: https://nextjs.org/docs/messages/built-in-next-font
```

```shell
$ npx @next/codemod@latest built-in-next-font . --force                                                                 [2:01:17]
WARNING: Git directory is not clean. Forcibly continuing.
Executing command: jscodeshift --verbose=2 --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform ~/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/built-in-next-font.js .
Processing 53 files... 
Spawning 7 workers...
Sending 8 files to free worker...
 NOC global.d.ts
 NOC env.d.ts
 NOC jest.config.ts
 NOC next-sitemap.config.js
 NOC postcss.config.js
 NOC jest.setup.ts
 NOC next-env.d.ts
 NOC next.config.js
All done. 
Results: 
0 errors
52 unmodified
0 skipped
1 ok
Uninstalling `@next/font`
yarn remove v1.22.19
[1/2] 🗑  Removing module @next/font...
[2/2] 🔨  Regenerating lockfile and installing missing dependencies...
[#################################################################################################----------------------] 637/779
```

And It's Solved the Error!
references: [NEXT.js Built-in Font migration guides](https://nextjs.org/docs/messages/built-in-next-font)

_Originally posted by @AndrewDongminYoo in https://github.com/vercel/next.js/issues/45080#issuecomment-1510433491_
